# Generated by Django 2.0.4 on 2018-11-12 01:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PastBuySell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(max_length=5)),
                ('asset_class', models.CharField(max_length=10)),
                ('last_price', models.CharField(max_length=20)),
                ('trade_volume', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PastSwaps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto_pair', models.CharField(max_length=10)),
                ('last_price', models.CharField(max_length=10)),
                ('amount_of_crypto_spent', models.CharField(max_length=20)),
                ('amount_of_crypto_received', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='UserAddresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=150)),
            ],
        ),
    ]
