# Generated by Django 2.0.4 on 2018-11-15 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PastBuySell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(max_length=5)),
                ('asset_class', models.CharField(max_length=10)),
                ('last_price', models.CharField(max_length=20)),
                ('trade_volume', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PastSwaps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto_pair', models.CharField(max_length=10)),
                ('last_price', models.CharField(max_length=10)),
                ('amount_of_crypto_spent', models.CharField(max_length=20)),
                ('amount_of_crypto_received', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='UserAddresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserBinanceOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto_pair', models.CharField(max_length=10)),
                ('order_type', models.CharField(max_length=10)),
                ('buy_or_sell', models.CharField(max_length=5)),
                ('price', models.FloatField()),
                ('amount', models.FloatField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('exchange', models.CharField(default='Binance', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCredentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cb_api_key', models.CharField(max_length=200)),
                ('cb_secret_key', models.CharField(max_length=200)),
                ('gdax_api_key', models.CharField(max_length=200)),
                ('gdax_secret_key', models.CharField(max_length=200)),
                ('gdax_passphrase', models.CharField(max_length=200)),
                ('coinigy_api_key', models.CharField(max_length=200)),
                ('coinigy_api_secret', models.CharField(max_length=200)),
                ('binance_api_key', models.CharField(max_length=200)),
                ('binance_api_secret', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserGdaxOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto_pair', models.CharField(max_length=10)),
                ('order_type', models.CharField(max_length=10)),
                ('buy_or_sell', models.CharField(max_length=5)),
                ('price', models.FloatField()),
                ('amount', models.FloatField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('exchange', models.CharField(default='GDAX', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
